In [34]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame({
    'Name':['Alice','Bob',np.nan,'Eve'],
    'Age':[25,30,np.nan,23],
    'City':['Dhaka',np.nan,'Cumilla',np.nan]
})

In [ ]:
df

Name   Age     City
0  Alice  25.0    Dhaka
1    Bob  30.0      NaN
2    NaN   NaN  Cumilla
3    Eve  23.0      NaN

In [ ]:
df.dropna()

Name   Age   City
0  Alice  25.0  Dhaka

In [ ]:
df

Name   Age     City
0  Alice  25.0    Dhaka
1    Bob  30.0      NaN
2    NaN   NaN  Cumilla
3    Eve  23.0      NaN

In [ ]:
df=df.fillna(
    {
        'Name':'Unknown',
        'Age':df['Age'].mean(),
        'City':"Model Town"
    }
)

In [ ]:
df

Name   Age        City
0    Alice  25.0       Dhaka
1      Bob  30.0  Model Town
2  Unknown  26.0     Cumilla
3      Eve  23.0  Model Town

In [ ]:
df['Age']=df['Age'].astype(int)

In [ ]:
df

Name  Age        City
0    Alice   25       Dhaka
1      Bob   30  Model Town
2  Unknown   26     Cumilla
3      Eve   23  Model Town

In [ ]:
np_array=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Reshaped_array=np_array.reshape(3,2)

In [ ]:
Reshaped_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
Reshaped_array=np_array.reshape(1,6)

In [ ]:
Reshaped_array

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a=np.array([
    [1,2],
    [3,4]
    ])
b=np.array([   #ekhane doita array r modde column same hote pare row number change hote pare
    [5,6]
])

In [ ]:
v_stacked=np.vstack((a,b))

In [ ]:
v_stacked

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a=np.array([
    [1,2],
    [3,4]
    ])
b=np.array([
    [3,4,5],
    [2,5,7]
])

In [ ]:
h_stacked=np.hstack((a,b))

In [ ]:
h_stacked

array([[1, 2, 3, 4, 5],
       [3, 4, 2, 5, 7]])

In [ ]:
a=np.array([
    [1,2],
    [3,4]
    ])
b=np.array([
    [3,4],
    [2,5]
])

In [ ]:
d_stacked=np.dstack((a,b))

In [ ]:
d_stacked

array([[[1, 3],
        [2, 4]],

       [[3, 2],
        [4, 5]]])

In [ ]:
big_array=np.arange(10)

In [ ]:
big_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
split_array=np.split(big_array,2)

In [ ]:
split_array

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [35]:
split_array=np.split(big_array,5)
split_array


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [36]:
a=np.array([
    [1,2],
    [3,4]
    ])
split_array=np.split(a,2)
split_array

[array([[1, 2]]), array([[3, 4]])]

In [37]:
sorted_df=df.sort_values(by='Age')
sorted_df

Name  Age        City
3      Eve   23  Model Town
0    Alice   25       Dhaka
2  Unknown   26     Cumilla
1      Bob   30  Model Town

In [39]:
sorted_df=df.sort_values(by='Age',ascending=False)
sorted_df

Name  Age        City
1      Bob   30  Model Town
2  Unknown   26     Cumilla
0    Alice   25       Dhaka
3      Eve   23  Model Town

In [42]:
arr=np.array([4,5,3,6,9,3,9,8])


In [43]:
print(np.sort(arr))

[3 3 4 5 6 8 9 9]


In [44]:
print(np.sort(arr)[::-1])

[9 9 8 6 5 4 3 3]


In [45]:
!git clone https://github.com/arnayeem2001/Machine-Learning.git

Cloning into 'Machine-Learning'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), 22.71 KiB | 375.00 KiB/s, done.


In [46]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [47]:
!ls "/content/drive/MyDrive/Colab Notebooks"

 data_visualization_11_12_25.ipynb
 ML_intro_4_12_25.ipynb
'Numpy Attributes and Advanced Pandas Operations.ipynb'
 numpy-pandas_27_11_25.ipynb
 Ostad_numpy_intro.ipynb
 Ostad_pandas_intro.ipynb
 pandas_manipulation_12-01-23.ipynb
 Untitled0.ipynb
 Untitled1.ipynb


In [48]:
!mkdir -p /content/drive/MyDrive/github_projects/numpy_pandas
!ls /content/drive/MyDrive/github_projects

numpy_pandas  pandas_project
